version: "3"

services:
  db:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/hotel-files/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"

  spa:
    build:
      context: .
    container_name: spa
    ports:
      - "80:3000"
    depends_on:
      - api

  api:
    build:
      context: .
    container_name: api
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:docker@db:3306/hotel"


