version: "3"

services:
  db:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/hotel-files/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: hotel
    ports:
      - "3307:3306"

  app:
    environment:
      - IS_DOCKER=true
    build:
      context: ./backend
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
